-- display the table



-- Total waste generated , total population and population per capita
select sum(population_population_number_of_people) as TotalPopulation,round(sum(total_msw_total_msw_generated_tons_year),2) as TotalWaste , 
round((sum(population_population_number_of_people)/sum(total_msw_total_msw_generated_tons_year))*100, 2) as wasteGeneratedPerHead
from Waste_management.dbo.country_level_data


-- country and their total waste
select country_name,total_msw_total_msw_generated_tons_year as totalwaste
from Waste_management.dbo.country_level_data

-- population and waste generated 
select country_name,population_population_number_of_people as population ,
total_msw_total_msw_generated_tons_year as totalwaste
from Waste_management.dbo.country_level_data
order by totalwaste desc


-- waste per capita
select top 20 country_name , income_id,population_population_number_of_people as population ,
total_msw_total_msw_generated_tons_year as totalwaste,
round((total_msw_total_msw_generated_tons_year/population_population_number_of_people)*100, 2) AS wastepercentpercapita
from Waste_management.dbo.country_level_data
order by wastepercentpercapita desc

-- Different composition of waste of different country
select country_name, composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent, composition_other_percent,
composition_paper_cardboard_percent, composition_paper_cardboard_percent,
special_waste_e_waste_tons_year,special_waste_hazardous_waste_tons_year
from Waste_management.dbo.country_level_data

-- Different types of waste generated

select sum(composition_food_organic_waste_percent) as organic_waste,
sum(composition_glass_percent) as glass,
sum(composition_metal_percent) as metal,
sum(composition_other_percent) as other,
sum(composition_paper_cardboard_percent) as cardboard,
sum(composition_plastic_percent) as plastic,
sum(special_waste_e_waste_tons_year) as ewaste,
sum(special_waste_hazardous_waste_tons_year) as hazardouswaste
from Waste_management.dbo.country_level_data

-- waste generated by income group
select income_id,sum(population_population_number_of_people) as totalpopulation, 
sum(total_msw_total_msw_generated_tons_year) as totalwaste,
(sum(total_msw_total_msw_generated_tons_year)/sum(population_population_number_of_people))* 100 as percapitawastepercent
from Waste_management.dbo.country_level_data
group by income_id

